// Auto-generated by generate-i18n-constants.ts — DO NOT EDIT MANUALLY
// Source namespace: alert

export const ALERT_TRANSLATIONS = {
  DANGER: 'alert.danger',
  SUCCESS: 'alert.success',
  WARNING: 'alert.warning',
} as const;

export type ALERT_TRANSLATIONS_Keys = typeof ALERT_TRANSLATIONS[keyof typeof ALERT_TRANSLATIONS];
