// Auto-generated by generate-i18n-constants.ts — DO NOT EDIT MANUALLY
// Source namespace: comments

export const COMMENTS_TRANSLATIONS = {
  TITLE: 'comments.title',
  MOST_RELEVANT: 'comments.mostRelevant',
  NEWEST: 'comments.newest',
  NO_COMMENTS_TITLE: 'comments.noCommentsTitle',
  NO_COMMENTS_SUBTITLE: 'comments.noCommentsSubtitle',
  LOAD_MORE: 'comments.loadMore',
  LOADING_MORE: 'comments.loadingMore',
  LIKE: 'comments.like',
  REPLY: 'comments.reply',
  HIDE_REPLIES: 'comments.hideReplies',
  REPLYING_TO: 'comments.replyingTo',
  NO_REPLIES: 'comments.noReplies',
  WRITE_COMMENT: 'comments.writeComment',
  WRITE_REPLY: 'comments.writeReply',
} as const;

export type COMMENTS_TRANSLATIONS_Keys = typeof COMMENTS_TRANSLATIONS[keyof typeof COMMENTS_TRANSLATIONS];
