// Auto-generated by generate-i18n-constants.ts — DO NOT EDIT MANUALLY
// Source namespace: common

export const COMMON_TRANSLATIONS = {
  LOADING: 'common.loading',
  ERROR: 'common.error',
  SUCCESS: 'common.success',
  REACHED_END: 'common.reachedEnd',
  RETRY: 'common.retry',
  CLOSE: 'common.close',
  CANCEL: 'common.cancel',
  BACK: 'common.back',
} as const;

export type COMMON_TRANSLATIONS_Keys = typeof COMMON_TRANSLATIONS[keyof typeof COMMON_TRANSLATIONS];
