// Auto-generated by generate-i18n-constants.ts — DO NOT EDIT MANUALLY
// Source namespace: home

export const HOME_TRANSLATIONS = {
  TABS_FEED: 'home.tabs.feed',
  TABS_MY_POSTS: 'home.tabs.myPosts',
  TABS_COMMUNITY: 'home.tabs.community',
  TABS_SAVED: 'home.tabs.saved',
  SUGGESTED_FRIENDS: 'home.suggestedFriends',
  SHOW: 'home.show',
  LOADING_POSTS: 'home.loadingPosts',
  ERROR_RETRY: 'home.errorRetry',
  REACHED_END: 'home.reachedEnd',
  NO_POSTS_TITLE: 'home.noPostsTitle',
  NO_POSTS_SUBTITLE: 'home.noPostsSubtitle',
} as const;

export type HOME_TRANSLATIONS_Keys = typeof HOME_TRANSLATIONS[keyof typeof HOME_TRANSLATIONS];
