// Auto-generated by generate-i18n-constants.ts — DO NOT EDIT MANUALLY
// Source namespace: nav

export const NAV_TRANSLATIONS = {
  BRAND: 'nav.brand',
  FEED: 'nav.feed',
  PROFILE: 'nav.profile',
  NOTIFICATIONS: 'nav.notifications',
  SETTINGS: 'nav.settings',
  LOGOUT: 'nav.logout',
} as const;

export type NAV_TRANSLATIONS_Keys = typeof NAV_TRANSLATIONS[keyof typeof NAV_TRANSLATIONS];
