// Auto-generated by generate-i18n-constants.ts — DO NOT EDIT MANUALLY
// Source namespace: notifications

export const NOTIFICATIONS_TRANSLATIONS = {
  TITLE: 'notifications.title',
  UNREAD_ONE: 'notifications.unread_one',
  UNREAD_OTHER: 'notifications.unread_other',
  EMPTY_SUBTITLE: 'notifications.emptySubtitle',
  MARK_ALL_READ: 'notifications.markAllRead',
  LOADING: 'notifications.loading',
  LOAD_MORE: 'notifications.loadMore',
  LOADING_MORE: 'notifications.loadingMore',
  NO_NOTIFICATIONS_TITLE: 'notifications.noNotificationsTitle',
  NO_NOTIFICATIONS_SUBTITLE: 'notifications.noNotificationsSubtitle',
  TRY_AGAIN: 'notifications.tryAgain',
  READ: 'notifications.read',
  UNREAD: 'notifications.unread',
} as const;

export type NOTIFICATIONS_TRANSLATIONS_Keys = typeof NOTIFICATIONS_TRANSLATIONS[keyof typeof NOTIFICATIONS_TRANSLATIONS];
