// Auto-generated by generate-i18n-constants.ts — DO NOT EDIT MANUALLY
// Source namespace: post

export const POST_TRANSLATIONS = {
  PUBLIC: 'post.public',
  LIKE: 'post.like',
  COMMENT: 'post.comment',
  SHARE: 'post.share',
  LIKES: 'post.likes',
  LIKE_SINGULAR: 'post.like_singular',
  SHARES: 'post.shares',
  COMMENTS: 'post.comments',
  COMMENT_SINGULAR: 'post.comment_singular',
  VIEW_DETAILS: 'post.viewDetails',
  SAVE_POST: 'post.savePost',
  UNSAVE_POST: 'post.unsavePost',
  EDIT_POST: 'post.editPost',
  DELETE_POST: 'post.deletePost',
  BACK: 'post.back',
  BACK_TO_FEED: 'post.backToFeed',
  POSTING: 'post.posting',
  POST: 'post.post',
  WHATS_ON_MIND: 'post.whatsOnMind',
  PHOTO_VIDEO: 'post.photoVideo',
  FEELING: 'post.feeling',
  PRIVACY_PUBLIC: 'post.privacy.public',
  PRIVACY_FOLLOWING: 'post.privacy.following',
  PRIVACY_ONLY_ME: 'post.privacy.onlyMe',
  ORIGINAL_POST: 'post.originalPost',
  SHARED_POST_UNAVAILABLE: 'post.sharedPostUnavailable',
  MORE_OPTIONS: 'post.moreOptions',
  POST_DATE: 'post.postDate',
} as const;

export type POST_TRANSLATIONS_Keys = typeof POST_TRANSLATIONS[keyof typeof POST_TRANSLATIONS];
