// Auto-generated by generate-i18n-constants.ts — DO NOT EDIT MANUALLY
// Source namespace: profile

export const PROFILE_TRANSLATIONS = {
  LOADING: 'profile.loading',
  TRY_AGAIN: 'profile.tryAgain',
  MEMBER: 'profile.member',
  FOLLOWERS: 'profile.followers',
  FOLLOWING: 'profile.following',
  BOOKMARKS: 'profile.bookmarks',
  ABOUT: 'profile.about',
  ACTIVE_ON: 'profile.activeOn',
  MY_POSTS: 'profile.myPosts',
  SAVED: 'profile.saved',
  NO_POSTS_TITLE: 'profile.noPostsTitle',
  NO_POSTS_SUBTITLE: 'profile.noPostsSubtitle',
  NO_BOOKMARKS_TITLE: 'profile.noBookmarksTitle',
  NO_BOOKMARKS_SUBTITLE: 'profile.noBookmarksSubtitle',
  ADD_COVER: 'profile.addCover',
  VIEW_PHOTO: 'profile.viewPhoto',
  TOGGLE_PASSWORD: 'profile.togglePassword',
  TOGGLE_CONFIRM_PASSWORD: 'profile.toggleConfirmPassword',
} as const;

export type PROFILE_TRANSLATIONS_Keys = typeof PROFILE_TRANSLATIONS[keyof typeof PROFILE_TRANSLATIONS];
