// Auto-generated by generate-i18n-constants.ts — DO NOT EDIT MANUALLY
// Source namespace: suggestions

export const SUGGESTIONS_TRANSLATIONS = {
  TITLE: 'suggestions.title',
  SIDEBAR_TITLE: 'suggestions.sidebarTitle',
  LOADING: 'suggestions.loading',
  EMPTY: 'suggestions.empty',
  EMPTY_SUBTITLE: 'suggestions.emptySubtitle',
  SEARCH_PLACEHOLDER: 'suggestions.searchPlaceholder',
  SEARCH_SIDEBAR_PLACEHOLDER: 'suggestions.searchSidebarPlaceholder',
  FOLLOW: 'suggestions.follow',
  UNFOLLOW: 'suggestions.unfollow',
  FOLLOWERS: 'suggestions.followers',
  VIEW_MORE: 'suggestions.viewMore',
  LOAD_MORE: 'suggestions.loadMore',
  TRY_AGAIN: 'suggestions.tryAgain',
} as const;

export type SUGGESTIONS_TRANSLATIONS_Keys = typeof SUGGESTIONS_TRANSLATIONS[keyof typeof SUGGESTIONS_TRANSLATIONS];
